# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openengine/v1/engine.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'openengine/v1/engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openengine.v1 import kv_pb2 as openengine_dot_v1_dot_kv__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aopenengine/v1/engine.proto\x12\ropenengine.v1\x1a\x16openengine/v1/kv.proto\"\x16\n\x14GetEngineInfoRequest\"\xce\x02\n\nEngineInfo\x12\x13\n\x0b\x65ngine_name\x18\x01 \x01(\t\x12\x16\n\x0e\x65ngine_version\x18\x02 \x01(\t\x12\'\n\x04role\x18\x03 \x01(\x0e\x32\x19.openengine.v1.EngineRole\x12\x13\n\x0binstance_id\x18\x04 \x01(\t\x12\x18\n\x10supported_models\x18\x05 \x03(\t\x12\x33\n\x0bparallelism\x18\x06 \x01(\x0b\x32\x1e.openengine.v1.ParallelismInfo\x12\x34\n\x0ckv_connector\x18\x07 \x01(\x0b\x32\x1e.openengine.v1.KvConnectorInfo\x12\x17\n\x0fschema_revision\x18\x08 \x01(\r\x12\x1f\n\x17minimum_client_revision\x18\t \x01(\r\x12\x16\n\x0eschema_release\x18\n \x01(\t\"\xc1\x02\n\x0fParallelismInfo\x12!\n\x14tensor_parallel_size\x18\x01 \x01(\rH\x00\x88\x01\x01\x12#\n\x16pipeline_parallel_size\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x1f\n\x12\x64\x61ta_parallel_size\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x1f\n\x12\x64\x61ta_parallel_rank\x18\x04 \x01(\rH\x03\x88\x01\x01\x12%\n\x18\x64\x61ta_parallel_start_rank\x18\x05 \x01(\rH\x04\x88\x01\x01\x42\x17\n\x15_tensor_parallel_sizeB\x19\n\x17_pipeline_parallel_sizeB\x15\n\x13_data_parallel_sizeB\x15\n\x13_data_parallel_rankB\x1b\n\x19_data_parallel_start_rank*v\n\nEngineRole\x12\x1b\n\x17\x45NGINE_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x45NGINE_ROLE_AGGREGATED\x10\x01\x12\x17\n\x13\x45NGINE_ROLE_PREFILL\x10\x02\x12\x16\n\x12\x45NGINE_ROLE_DECODE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openengine.v1.engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENGINEROLE']._serialized_start=754
  _globals['_ENGINEROLE']._serialized_end=872
  _globals['_GETENGINEINFOREQUEST']._serialized_start=69
  _globals['_GETENGINEINFOREQUEST']._serialized_end=91
  _globals['_ENGINEINFO']._serialized_start=94
  _globals['_ENGINEINFO']._serialized_end=428
  _globals['_PARALLELISMINFO']._serialized_start=431
  _globals['_PARALLELISMINFO']._serialized_end=752
# @@protoc_insertion_point(module_scope)
