# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openengine/v1/input.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'openengine/v1/input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19openengine/v1/input.proto\x12\ropenengine.v1\"\x17\n\x08TokenIds\x12\x0b\n\x03ids\x18\x01 \x03(\r\"\x99\x01\n\tMediaItem\x12)\n\x08modality\x18\x01 \x01(\x0e\x32\x17.openengine.v1.Modality\x12\r\n\x03url\x18\x02 \x01(\tH\x00\x12\x12\n\x08\x64\x61ta_uri\x18\x03 \x01(\tH\x00\x12\x13\n\traw_bytes\x18\x04 \x01(\x0cH\x00\x12\x11\n\tmime_type\x18\x05 \x01(\t\x12\x0c\n\x04uuid\x18\x06 \x01(\tB\x08\n\x06source\"\x86\x01\n\x13MultimodalTaskInput\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12,\n\ttoken_ids\x18\x02 \x01(\x0b\x32\x17.openengine.v1.TokenIdsH\x00\x12\'\n\x05media\x18\x03 \x03(\x0b\x32\x18.openengine.v1.MediaItemB\x08\n\x06prompt\"\x9d\x01\n\tTaskInput\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0e\n\x04text\x18\x02 \x01(\tH\x00\x12,\n\ttoken_ids\x18\x03 \x01(\x0b\x32\x17.openengine.v1.TokenIdsH\x00\x12\x38\n\nmultimodal\x18\x04 \x01(\x0b\x32\".openengine.v1.MultimodalTaskInputH\x00\x42\x07\n\x05input*`\n\x08Modality\x12\x18\n\x14MODALITY_UNSPECIFIED\x10\x00\x12\x12\n\x0eMODALITY_IMAGE\x10\x01\x12\x12\n\x0eMODALITY_VIDEO\x10\x02\x12\x12\n\x0eMODALITY_AUDIO\x10\x03*\x90\x01\n\x0fMediaSourceType\x12!\n\x1dMEDIA_SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15MEDIA_SOURCE_TYPE_URL\x10\x01\x12\x1e\n\x1aMEDIA_SOURCE_TYPE_DATA_URI\x10\x02\x12\x1f\n\x1bMEDIA_SOURCE_TYPE_RAW_BYTES\x10\x03*\x89\x01\n\rTaskInputType\x12\x1f\n\x1bTASK_INPUT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14TASK_INPUT_TYPE_TEXT\x10\x01\x12\x1d\n\x19TASK_INPUT_TYPE_TOKEN_IDS\x10\x02\x12\x1e\n\x1aTASK_INPUT_TYPE_MULTIMODAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openengine.v1.input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODALITY']._serialized_start=522
  _globals['_MODALITY']._serialized_end=618
  _globals['_MEDIASOURCETYPE']._serialized_start=621
  _globals['_MEDIASOURCETYPE']._serialized_end=765
  _globals['_TASKINPUTTYPE']._serialized_start=768
  _globals['_TASKINPUTTYPE']._serialized_end=905
  _globals['_TOKENIDS']._serialized_start=44
  _globals['_TOKENIDS']._serialized_end=67
  _globals['_MEDIAITEM']._serialized_start=70
  _globals['_MEDIAITEM']._serialized_end=223
  _globals['_MULTIMODALTASKINPUT']._serialized_start=226
  _globals['_MULTIMODALTASKINPUT']._serialized_end=360
  _globals['_TASKINPUT']._serialized_start=363
  _globals['_TASKINPUT']._serialized_end=520
# @@protoc_insertion_point(module_scope)
