# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openengine.v1 import engine_pb2 as openengine_dot_v1_dot_engine__pb2
from openengine.v1 import generation_pb2 as openengine_dot_v1_dot_generation__pb2
from openengine.v1 import kv_pb2 as openengine_dot_v1_dot_kv__pb2
from openengine.v1 import lifecycle_pb2 as openengine_dot_v1_dot_lifecycle__pb2
from openengine.v1 import lora_pb2 as openengine_dot_v1_dot_lora__pb2
from openengine.v1 import model_pb2 as openengine_dot_v1_dot_model__pb2
from openengine.v1 import observability_pb2 as openengine_dot_v1_dot_observability__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in openengine/v1/openengine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/openengine.v1.OpenEngine/Generate',
                request_serializer=openengine_dot_v1_dot_generation__pb2.GenerateRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_generation__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GetEngineInfo = channel.unary_unary(
                '/openengine.v1.OpenEngine/GetEngineInfo',
                request_serializer=openengine_dot_v1_dot_engine__pb2.GetEngineInfoRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_engine__pb2.EngineInfo.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/openengine.v1.OpenEngine/GetModelInfo',
                request_serializer=openengine_dot_v1_dot_model__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_model__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.GetLoad = channel.unary_unary(
                '/openengine.v1.OpenEngine/GetLoad',
                request_serializer=openengine_dot_v1_dot_observability__pb2.GetLoadRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_observability__pb2.LoadInfo.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/openengine.v1.OpenEngine/Health',
                request_serializer=openengine_dot_v1_dot_lifecycle__pb2.HealthRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lifecycle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/openengine.v1.OpenEngine/Abort',
                request_serializer=openengine_dot_v1_dot_lifecycle__pb2.AbortRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lifecycle__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.Drain = channel.unary_stream(
                '/openengine.v1.OpenEngine/Drain',
                request_serializer=openengine_dot_v1_dot_lifecycle__pb2.DrainRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lifecycle__pb2.DrainResponse.FromString,
                _registered_method=True)
        self.LoadLora = channel.unary_unary(
                '/openengine.v1.OpenEngine/LoadLora',
                request_serializer=openengine_dot_v1_dot_lora__pb2.LoadLoraRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lora__pb2.LoadLoraResponse.FromString,
                _registered_method=True)
        self.UnloadLora = channel.unary_unary(
                '/openengine.v1.OpenEngine/UnloadLora',
                request_serializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraResponse.FromString,
                _registered_method=True)
        self.ListLoras = channel.unary_unary(
                '/openengine.v1.OpenEngine/ListLoras',
                request_serializer=openengine_dot_v1_dot_lora__pb2.ListLorasRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lora__pb2.ListLorasResponse.FromString,
                _registered_method=True)
        self.GetKvConnectorInfo = channel.unary_unary(
                '/openengine.v1.OpenEngine/GetKvConnectorInfo',
                request_serializer=openengine_dot_v1_dot_kv__pb2.GetKvConnectorInfoRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_kv__pb2.KvConnectorInfo.FromString,
                _registered_method=True)
        self.GetKvEventSources = channel.unary_unary(
                '/openengine.v1.OpenEngine/GetKvEventSources',
                request_serializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesResponse.FromString,
                _registered_method=True)
        self.SubscribeKvEvents = channel.unary_stream(
                '/openengine.v1.OpenEngine/SubscribeKvEvents',
                request_serializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsResponse.FromString,
                _registered_method=True)
        self.SubscribeRuntimeEvents = channel.unary_stream(
                '/openengine.v1.OpenEngine/SubscribeRuntimeEvents',
                request_serializer=openengine_dot_v1_dot_observability__pb2.SubscribeRuntimeEventsRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_observability__pb2.SubscribeRuntimeEventsResponse.FromString,
                _registered_method=True)


class OpenEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Core inference path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineInfo(self, request, context):
        """Runtime metadata and scheduling state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health and lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadLora(self, request, context):
        """LoRA lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadLora(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKvConnectorInfo(self, request, context):
        """Disaggregated serving / KV transfer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKvEventSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeKvEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRuntimeEvents(self, request, context):
        """Structured runtime events for planners/controllers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=openengine_dot_v1_dot_generation__pb2.GenerateRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_generation__pb2.GenerateResponse.SerializeToString,
            ),
            'GetEngineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineInfo,
                    request_deserializer=openengine_dot_v1_dot_engine__pb2.GetEngineInfoRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_engine__pb2.EngineInfo.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=openengine_dot_v1_dot_model__pb2.GetModelInfoRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_model__pb2.ModelInfo.SerializeToString,
            ),
            'GetLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoad,
                    request_deserializer=openengine_dot_v1_dot_observability__pb2.GetLoadRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_observability__pb2.LoadInfo.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=openengine_dot_v1_dot_lifecycle__pb2.HealthRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lifecycle__pb2.HealthResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=openengine_dot_v1_dot_lifecycle__pb2.AbortRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lifecycle__pb2.AbortResponse.SerializeToString,
            ),
            'Drain': grpc.unary_stream_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=openengine_dot_v1_dot_lifecycle__pb2.DrainRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lifecycle__pb2.DrainResponse.SerializeToString,
            ),
            'LoadLora': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadLora,
                    request_deserializer=openengine_dot_v1_dot_lora__pb2.LoadLoraRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lora__pb2.LoadLoraResponse.SerializeToString,
            ),
            'UnloadLora': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadLora,
                    request_deserializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraResponse.SerializeToString,
            ),
            'ListLoras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoras,
                    request_deserializer=openengine_dot_v1_dot_lora__pb2.ListLorasRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lora__pb2.ListLorasResponse.SerializeToString,
            ),
            'GetKvConnectorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKvConnectorInfo,
                    request_deserializer=openengine_dot_v1_dot_kv__pb2.GetKvConnectorInfoRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_kv__pb2.KvConnectorInfo.SerializeToString,
            ),
            'GetKvEventSources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKvEventSources,
                    request_deserializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesResponse.SerializeToString,
            ),
            'SubscribeKvEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeKvEvents,
                    request_deserializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsResponse.SerializeToString,
            ),
            'SubscribeRuntimeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRuntimeEvents,
                    request_deserializer=openengine_dot_v1_dot_observability__pb2.SubscribeRuntimeEventsRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_observability__pb2.SubscribeRuntimeEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openengine.v1.OpenEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openengine.v1.OpenEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openengine.v1.OpenEngine/Generate',
            openengine_dot_v1_dot_generation__pb2.GenerateRequest.SerializeToString,
            openengine_dot_v1_dot_generation__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/GetEngineInfo',
            openengine_dot_v1_dot_engine__pb2.GetEngineInfoRequest.SerializeToString,
            openengine_dot_v1_dot_engine__pb2.EngineInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/GetModelInfo',
            openengine_dot_v1_dot_model__pb2.GetModelInfoRequest.SerializeToString,
            openengine_dot_v1_dot_model__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/GetLoad',
            openengine_dot_v1_dot_observability__pb2.GetLoadRequest.SerializeToString,
            openengine_dot_v1_dot_observability__pb2.LoadInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/Health',
            openengine_dot_v1_dot_lifecycle__pb2.HealthRequest.SerializeToString,
            openengine_dot_v1_dot_lifecycle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/Abort',
            openengine_dot_v1_dot_lifecycle__pb2.AbortRequest.SerializeToString,
            openengine_dot_v1_dot_lifecycle__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openengine.v1.OpenEngine/Drain',
            openengine_dot_v1_dot_lifecycle__pb2.DrainRequest.SerializeToString,
            openengine_dot_v1_dot_lifecycle__pb2.DrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadLora(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/LoadLora',
            openengine_dot_v1_dot_lora__pb2.LoadLoraRequest.SerializeToString,
            openengine_dot_v1_dot_lora__pb2.LoadLoraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadLora(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/UnloadLora',
            openengine_dot_v1_dot_lora__pb2.UnloadLoraRequest.SerializeToString,
            openengine_dot_v1_dot_lora__pb2.UnloadLoraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/ListLoras',
            openengine_dot_v1_dot_lora__pb2.ListLorasRequest.SerializeToString,
            openengine_dot_v1_dot_lora__pb2.ListLorasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKvConnectorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/GetKvConnectorInfo',
            openengine_dot_v1_dot_kv__pb2.GetKvConnectorInfoRequest.SerializeToString,
            openengine_dot_v1_dot_kv__pb2.KvConnectorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKvEventSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.OpenEngine/GetKvEventSources',
            openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesRequest.SerializeToString,
            openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeKvEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openengine.v1.OpenEngine/SubscribeKvEvents',
            openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsRequest.SerializeToString,
            openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRuntimeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openengine.v1.OpenEngine/SubscribeRuntimeEvents',
            openengine_dot_v1_dot_observability__pb2.SubscribeRuntimeEventsRequest.SerializeToString,
            openengine_dot_v1_dot_observability__pb2.SubscribeRuntimeEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
