# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openengine/v1/tasks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'openengine/v1/tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19openengine/v1/tasks.proto\x12\ropenengine.v1\x1a\x1cgoogle/protobuf/struct.proto\"r\n\x12TaskRequestContext\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x11\n\tlora_name\x18\x03 \x01(\t\x12&\n\x05\x65xtra\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"1\n\x10\x44\x65nseFloatTensor\x12\r\n\x05shape\x18\x01 \x03(\x04\x12\x0e\n\x06values\x18\x02 \x03(\x02\"[\n\tTaskUsage\x12\x14\n\x0cinput_tokens\x18\x01 \x01(\x04\x12 \n\x13\x63\x61\x63hed_input_tokens\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\x16\n\x14_cached_input_tokens*\x89\x01\n\x15TaskOutputGranularity\x12\'\n#TASK_OUTPUT_GRANULARITY_UNSPECIFIED\x10\x00\x12$\n TASK_OUTPUT_GRANULARITY_SEQUENCE\x10\x01\x12!\n\x1dTASK_OUTPUT_GRANULARITY_TOKEN\x10\x02*\xc1\x02\n\x12TaskValueSemantics\x12$\n TASK_VALUE_SEMANTICS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bTASK_VALUE_SEMANTICS_LOGITS\x10\x01\x12&\n\"TASK_VALUE_SEMANTICS_PROBABILITIES\x10\x02\x12*\n&TASK_VALUE_SEMANTICS_LOG_PROBABILITIES\x10\x03\x12#\n\x1fTASK_VALUE_SEMANTICS_SIMILARITY\x10\x04\x12\"\n\x1eTASK_VALUE_SEMANTICS_RELEVANCE\x10\x05\x12\x1f\n\x1bTASK_VALUE_SEMANTICS_REWARD\x10\x06\x12&\n\"TASK_VALUE_SEMANTICS_MODEL_DEFINED\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openengine.v1.tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKOUTPUTGRANULARITY']._serialized_start=335
  _globals['_TASKOUTPUTGRANULARITY']._serialized_end=472
  _globals['_TASKVALUESEMANTICS']._serialized_start=475
  _globals['_TASKVALUESEMANTICS']._serialized_end=796
  _globals['_TASKREQUESTCONTEXT']._serialized_start=74
  _globals['_TASKREQUESTCONTEXT']._serialized_end=188
  _globals['_DENSEFLOATTENSOR']._serialized_start=190
  _globals['_DENSEFLOATTENSOR']._serialized_end=239
  _globals['_TASKUSAGE']._serialized_start=241
  _globals['_TASKUSAGE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
